---

- name: Adding Kafka group
  group:
    gid: "{{ KAFKA_GID }}"
    name: "{{ KAFKA_USER }}"

- name: Adding Kafka user
  user:
    name: "{{ KAFKA_USER }}"
    uid: "{{ KAFKA_UID }}"
    group: "{{ KAFKA_USER }}"
    home: "{{ KAFKA_HOME }}"
    create_home: no
    shell: /bin/bash

- name: Installing OpenJDK 8 JRE
  apt:
    name: openjdk-8-jre-headless
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ KAFKA_USER }}"
    group: "{{ KAFKA_USER }}"
  loop:
    - "{{ KAFKA_HOME }}"
    - "{{ KAFKA_LOGS_PATH }}"

- name: Downloading and Extracting Kafka
  unarchive:
    remote_src: yes
    src: "https://mirrors.ocf.berkeley.edu/apache/kafka/{{ KAFKA_VERSION }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz"
    dest: "{{ KAFKA_HOME }}"
    owner: "{{ KAFKA_USER }}"
    group: "{{ KAFKA_USER }}"

- name: Copy Kafka config
  copy:
    src: server.properties
    dest: "{{ KAFKA_HOME }}/config/"

- name: Copy Kafka scripts
  copy:
    src: scripts/
    dest: "{{ KAFKA_HOME }}/scripts/"
